# Generated by Django 6.0.6 on 2026-06-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📁', max_length=50)),
                ('color', models.CharField(default='#60a5fa', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='vocab.folder')),
            ],
            options={
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='English word or phrase.', max_length=300)),
                ('ipa', models.CharField(blank=True, help_text='IPA pronunciation.', max_length=200)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adj', 'Adjective'), ('adv', 'Adverb'), ('prep', 'Preposition'), ('conj', 'Conjunction'), ('pron', 'Pronoun'), ('det', 'Determiner'), ('interj', 'Interjection'), ('phrase', 'Phrase'), ('idiom', 'Idiom')], default='noun', max_length=20)),
                ('definition_en', models.TextField(blank=True, help_text='English definition.')),
                ('definition_vi', models.TextField(blank=True, help_text='Vietnamese meaning.')),
                ('example_sentences', models.JSONField(blank=True, default=list, help_text='List of example sentences.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='word_images/')),
                ('audio_url', models.URLField(blank=True, help_text='URL to pronunciation audio.')),
                ('collocations', models.JSONField(blank=True, default=list)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('antonyms', models.JSONField(blank=True, default=list)),
                ('context_paragraph', models.TextField(blank=True, help_text='A paragraph using the word in natural context.')),
                ('user_notes', models.TextField(blank=True, help_text="User's own notes.")),
                ('user_explanation', models.TextField(blank=True, help_text="User's explanation (Feynman technique).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocab.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'deck', 'term')},
            },
        ),
        migrations.CreateModel(
            name='CardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=0, help_text='Interval in days.')),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('leitner_box', models.IntegerField(default=1, help_text='Leitner box number (1-5).')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('young', 'Young'), ('mature', 'Mature'), ('relearn', 'Relearn')], default='new', max_length=10)),
                ('quality_history', models.JSONField(blank=True, default=list, help_text='History of review quality ratings.')),
                ('total_reviews', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_reviews', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vocab.word')),
            ],
            options={
                'verbose_name': 'Card Review',
                'verbose_name_plural': 'Card Reviews',
                'unique_together': {('user', 'word')},
            },
        ),
    ]
